# Generated by Django 5.2.8 on 2026-01-05 03:04

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(default=myapp.models.default_city, max_length=30)),
                ('state', models.CharField(default='CA', max_length=2)),
            ],
        ),
    ]
